### ISSUE TITLE
Syncfusion build error in angular 6 application

### ISSUE THREAD

**Issue by chelvan247** [syncfusion/ej2-angular-ui-components#171]
We are working with angular 6, latest (19.1.58) @syncfusion/ej2-angular-documenteditor, which throws an error while we build the application "ERROR in node_modules/@syncfusion/ej2-angular-base/src/form-base.d.ts(10,34): error TS1039: Initializers are not allowed in ambient contexts"

**Comment by Suriya-Murugan** [comment]
Hi chelvan247,

We suspect the issue because of you using lower version of Typescript. Can you please upgrade your typescript and angular CLI to latest version to resolve the issue?

Please check below link for reference:

https://github.com/angular/angular-cli/issues/5693#issuecomment-289515125 

Please let us know if you still facing issue.

Regards,
Suriya M.

**Comment by syncsiva** [comment]
Closing the issue since no activity for 6 months.
